name: ci

on:
  pull_request:
    branches:
      - "release/*"
      - "master"

  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-buster
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          pip install git+https://github.com/virtool/virtool-cli.git
          virtool build -src src
          gzip reference.json
