name: ci

on:
  pull_request:
    branches:
      - "release/*"
      - "master"

  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-buster
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          pip install virtool-cli
          virtool ref build -src src
          gzip reference.json
      - name: Save JSON
        uses: actions/upload-artifact@v3
        with:
          name: reference.json.gz
          path: reference.json.gz
